# Generated by Django 6.0.5 on 2026-05-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
    ]
